USE [master]
GO

/****** Object:  Database [receptkonyv]    Script Date: 2023. 05. 30. 18:59:21 ******/
CREATE DATABASE [receptkonyv]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'receptkonyv', FILENAME = N'F:\SQL_szerver\MSSQL15.MSSQLSERVER\MSSQL\DATA\receptkonyv.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'receptkonyv_log', FILENAME = N'F:\SQL_szerver\MSSQL15.MSSQLSERVER\MSSQL\DATA\receptkonyv_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [receptkonyv].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [receptkonyv] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [receptkonyv] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [receptkonyv] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [receptkonyv] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [receptkonyv] SET ARITHABORT OFF 
GO

ALTER DATABASE [receptkonyv] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [receptkonyv] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [receptkonyv] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [receptkonyv] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [receptkonyv] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [receptkonyv] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [receptkonyv] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [receptkonyv] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [receptkonyv] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [receptkonyv] SET  ENABLE_BROKER 
GO

ALTER DATABASE [receptkonyv] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [receptkonyv] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [receptkonyv] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [receptkonyv] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [receptkonyv] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [receptkonyv] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [receptkonyv] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [receptkonyv] SET RECOVERY FULL 
GO

ALTER DATABASE [receptkonyv] SET  MULTI_USER 
GO

ALTER DATABASE [receptkonyv] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [receptkonyv] SET DB_CHAINING OFF 
GO

ALTER DATABASE [receptkonyv] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [receptkonyv] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [receptkonyv] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [receptkonyv] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [receptkonyv] SET QUERY_STORE = OFF
GO

ALTER DATABASE [receptkonyv] SET  READ_WRITE 
GO


